[env:esp32-s3-devkitc-1]
platform_packages = framework-arduinoespressif32@3.20014.231204
platform = espressif32@6.13.0
board = esp32-s3-devkitc-1
framework = arduino
build_type = debug
build_src_filter = -<*> +<main_DrnBrdg.cpp>
board_build.arduino.memory_type = dio_qspi
board_build.flash_mode = dio
board_upload.flash_size = 4MB
upload_speed = 115200
upload_flags = --no-stub
board_upload.maximum_size = 4194304
board_build.partitions = default.csv
lib_deps =  https://github.com/mavlink/c_library_v2.git
            https://github.com/adafruit/Adafruit_NeoPixel.git
build_flags = -I include
              -DARDUINO_USB_CDC_ON_BOOT=1
              -I .pio/libdeps/esp32-s3-devkitc-1/c_library_v2/common
               -I .pio/libdeps/esp32-s3-devkitc-1/c_library_v2/ardupilotmega
